# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2e395a9221906d2b53f54e82421f069e"
name = "resellify"
handle = "resellify-widget-extention"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
type = "checkout_ui_extension"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[extensions.targeting]
target = "purchase.thank-you.render-after"
