# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d850df0b4a818eddfb5c6e36712c8d73"
name = "resellify"
handle = "resellify-widget-extention"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
type = "checkout_ui_extension"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[extensions.targeting]
target = "purchase.thank-you.render-after"
