name = "resellify-post-purchase-ui-extension"
type = "checkout_post_purchase"

[access.admin]
direct_api_mode = "online"

[access_scopes]
scopes = "read_orders,read_products,unauthenticated_read_product_listings"



# [[metafields]]
# namespace = "my-namespace"
# key = "my-key"

# [[metafields]]
# namespace = "my-namespace"
# key = "my-key-2"
